# Generated by Django 2.2.2 on 2019-08-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Launches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Flight_Number', models.IntegerField()),
                ('Flight_date', models.TextField()),
                ('Rocket_Name', models.TextField()),
                ('Rocket_Id', models.IntegerField()),
                ('Mission_Patch_Link', models.URLField()),
                ('Mission_Video_Link', models.URLField()),
            ],
        ),
    ]
