# Generated by Django 2.2.2 on 2019-08-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freegio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launches',
            name='Rocket_Id',
            field=models.TextField(),
        ),
    ]
