# Generated by Django 2.2.2 on 2019-08-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freegio', '0002_auto_20190809_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launches',
            name='Mission_Patch_Link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='launches',
            name='Mission_Video_Link',
            field=models.URLField(null=True),
        ),
    ]
