# Generated by Django 2.2.2 on 2019-08-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freegio', '0004_auto_20190809_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='launches',
            name='Mission_Patch_Link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='launches',
            name='Mission_Video_Link',
            field=models.URLField(null=True),
        ),
    ]
