# Generated by Django 2.2.2 on 2019-08-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freegio', '0005_auto_20190809_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='launches',
            name='Mission_name',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
