# Generated by Django 2.2.2 on 2019-08-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Freegio', '0007_auto_20190809_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launches',
            name='Flight_date',
            field=models.DateTimeField(),
        ),
    ]
